# Generated by Django 3.1.2 on 2020-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_store',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('mEmail', models.CharField(max_length=50)),
                ('subscribed_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
