# Generated by Django 3.1.2 on 2020-12-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201218_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_store',
            name='mEmail',
            field=models.CharField(max_length=254),
        ),
    ]
